
const express=require("express"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),path=require("path");
const app=express(),db=new Database("flash-wash.db"),SECRET=process.env.JWT_SECRET||"CHANGE_THIS_SECRET_BEFORE_PUBLIC_DEPLOYMENT";
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE,password_hash TEXT,role TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_name TEXT,phone TEXT,area TEXT,car_type TEXT,service TEXT,employee_id INTEGER,appointment TEXT,price INTEGER,status TEXT DEFAULT 'جديد',notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,created_by INTEGER);
CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_name TEXT,phone TEXT,plan TEXT,price INTEGER,washes_total INTEGER DEFAULT 5,washes_used INTEGER DEFAULT 0,start_date TEXT,end_date TEXT,day TEXT,time TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,category TEXT,amount INTEGER,date TEXT,notes TEXT,created_by INTEGER);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,action TEXT,entity TEXT,entity_id INTEGER,details TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT);
`);
const seedUsers=[["hassan","Flash@2026!","admin"],["haider","Flash@2026!","admin"]];
for(const [u,p,r] of seedUsers){const ex=db.prepare("SELECT id FROM users WHERE username=?").get(u);if(!ex)db.prepare("INSERT INTO users(username,password_hash,role) VALUES(?,?,?)").run(u,bcrypt.hashSync(p,10),r)}
for(const n of ["عباس","أيمن","فهد","سيف"])db.prepare("INSERT OR IGNORE INTO employees(name) VALUES(?)").run(n);
const defaults={"عادي-ناصية":15000,"عادي-عالية":18000,"VIP-ناصية":20000,"VIP-عالية":20000,"اشتراك-ناصية":58000,"اشتراك-عالية":69000,"اشتراك-VIP":78000};
for(const [k,v] of Object.entries(defaults))db.prepare("INSERT OR IGNORE INTO settings(k,v) VALUES(?,?)").run(k,String(v));
const today=()=>new Date().toISOString().slice(0,10);
function auth(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"غير مسجل الدخول"});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:"جلسة منتهية"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"صلاحية غير كافية"});next()}
function audit(u,a,e,id,d=""){db.prepare("INSERT INTO audit(user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?)").run(u,a,e,id,d)}
app.post("/api/login",(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE username=? AND active=1").get(req.body.username);if(!u||!bcrypt.compareSync(req.body.password,u.password_hash))return res.status(401).json({error:"اسم المستخدم أو كلمة المرور غير صحيحة"});const token=jwt.sign({id:u.id,username:u.username,role:u.role},SECRET,{expiresIn:"12h"});res.json({token,user:{username:u.username,role:u.role}})});
app.get("/api/me",auth,(req,res)=>res.json(req.user));
app.get("/api/dashboard",auth,(req,res)=>{const d=today(),o=db.prepare("SELECT COUNT(*) c,COALESCE(SUM(price),0) r FROM orders WHERE substr(created_at,1,10)=? AND status!='ملغي'").get(d),e=db.prepare("SELECT COALESCE(SUM(amount),0) x FROM expenses WHERE date=?").get(d),s=db.prepare("SELECT COUNT(*) c FROM subscriptions WHERE end_date>=?").get(d);res.json({orders:o.c,revenue:o.r,expenses:e.x,net:o.r-e.x,subscriptions:s.c,workers:db.prepare("SELECT COUNT(*) c FROM employees WHERE active=1").get().c})});
app.get("/api/employees",auth,(req,res)=>res.json(db.prepare("SELECT * FROM employees WHERE active=1").all()));
app.get("/api/orders",auth,(req,res)=>{let rows=db.prepare("SELECT o.*,e.name employee FROM orders o LEFT JOIN employees e ON e.id=o.employee_id ORDER BY o.id DESC").all();if(req.user.role==="worker")rows=rows.filter(x=>x.employee_id===req.user.employee_id);res.json(rows)});
app.post("/api/orders",auth,(req,res)=>{const b=req.body,r=db.prepare(`INSERT INTO orders(customer_name,phone,area,car_type,service,employee_id,appointment,price,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(b.customer_name,b.phone,b.area,b.car_type,b.service,b.employee_id,b.appointment,b.price,b.status||"جديد",b.notes||"",req.user.id);audit(req.user.id,"إضافة","order",r.lastInsertRowid,JSON.stringify(b));res.json({id:r.lastInsertRowid})});
app.patch("/api/orders/:id",auth,(req,res)=>{const old=db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);if(req.user.role==="worker"&&old.employee_id!==req.user.employee_id)return res.status(403).json({error:"لا يمكنك تعديل طلب غير تابع لك"});const b=req.body;db.prepare("UPDATE orders SET status=COALESCE(?,status),price=COALESCE(?,price),notes=COALESCE(?,notes) WHERE id=?").run(b.status,b.price,b.notes,req.params.id);audit(req.user.id,"تعديل","order",req.params.id,JSON.stringify({before:old,after:b}));res.json({ok:true})});
app.get("/api/customers",auth,(req,res)=>res.json(db.prepare(`SELECT phone,MAX(customer_name) customer_name,MAX(area) area,COUNT(*) washes,COALESCE(SUM(price),0) total_paid,MAX(created_at) last_wash FROM orders WHERE phone!='' GROUP BY phone ORDER BY last_wash DESC`).all()));
app.get("/api/subscriptions",auth,(req,res)=>res.json(db.prepare("SELECT * FROM subscriptions ORDER BY id DESC").all()));
app.post("/api/subscriptions",auth,(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({error:"الإدارة فقط"});let b=req.body,r=db.prepare(`INSERT INTO subscriptions(customer_name,phone,plan,price,washes_total,washes_used,start_date,end_date,day,time,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(b.customer_name,b.phone,b.plan,b.price,b.washes_total||5,0,b.start_date,b.end_date,b.day||"",b.time||"",b.notes||"");audit(req.user.id,"إضافة","subscription",r.lastInsertRowid,JSON.stringify(b));res.json({id:r.lastInsertRowid})});
app.patch("/api/subscriptions/:id/use",auth,admin,(req,res)=>{db.prepare("UPDATE subscriptions SET washes_used=MIN(washes_total,washes_used+1) WHERE id=?").run(req.params.id);audit(req.user.id,"استخدام غسلة","subscription",req.params.id);res.json({ok:true})});
app.get("/api/expenses",auth,(req,res)=>res.json(db.prepare("SELECT * FROM expenses ORDER BY id DESC").all()));
app.post("/api/expenses",auth,admin,(req,res)=>{let b=req.body,r=db.prepare("INSERT INTO expenses(title,category,amount,date,notes,created_by) VALUES(?,?,?,?,?,?)").run(b.title,b.category,b.amount,b.date||today(),b.notes||"",req.user.id);audit(req.user.id,"إضافة","expense",r.lastInsertRowid,JSON.stringify(b));res.json({id:r.lastInsertRowid})});
app.get("/api/reports",auth,(req,res)=>{const byEmp=db.prepare(`SELECT COALESCE(e.name,'غير محدد') employee,COUNT(o.id) orders,COALESCE(SUM(o.price),0) revenue FROM orders o LEFT JOIN employees e ON e.id=o.employee_id WHERE o.status!='ملغي' GROUP BY employee ORDER BY revenue DESC`).all();const byService=db.prepare("SELECT service,COUNT(*) orders,COALESCE(SUM(price),0) revenue FROM orders WHERE status!='ملغي' GROUP BY service").all();res.json({byEmp,byService})});
app.get("/api/audit",auth,admin,(req,res)=>res.json(db.prepare(`SELECT a.*,u.username FROM audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 300`).all()));
app.get("/api/users",auth,admin,(req,res)=>res.json(db.prepare("SELECT id,username,role,active FROM users ORDER BY id").all()));
app.post("/api/users",auth,admin,(req,res)=>{let p=req.body;if(!p.username||!p.password)return res.status(400).json({error:"بيانات ناقصة"});try{let r=db.prepare("INSERT INTO users(username,password_hash,role) VALUES(?,?,?)").run(p.username,bcrypt.hashSync(p.password,10),p.role||"worker");audit(req.user.id,"إضافة مستخدم","user",r.lastInsertRowid,p.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:"اسم المستخدم موجود"})}});
app.get("/api/backup",auth,admin,(req,res)=>res.json({date:new Date().toISOString(),users:db.prepare("SELECT id,username,role,active FROM users").all(),employees:db.prepare("SELECT * FROM employees").all(),orders:db.prepare("SELECT * FROM orders").all(),subscriptions:db.prepare("SELECT * FROM subscriptions").all(),expenses:db.prepare("SELECT * FROM expenses").all(),audit:db.prepare("SELECT * FROM audit").all(),settings:db.prepare("SELECT * FROM settings").all()}));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
app.listen(process.env.PORT||3000,()=>console.log("Flash Wash V3 ready"));
